esmini_home: /opt/esmini/
extra_paths:
  - /opt/esmini/resources/xodr/
  - /opt/esmini/resources/xosc/
  - /opt/esmini/resources/models/
  - /opt/esmini/resources/openx-assets/catalogs/
  - /sbsvf/scenarios/tw/maps/

window: [60, 1920, 1920, 2160]
